/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWithdrawRouteImport } from './routes/_authenticated/withdraw'
import { Route as AuthenticatedReferralsRouteImport } from './routes/_authenticated/referrals'
import { Route as AuthenticatedInvestRouteImport } from './routes/_authenticated/invest'
import { Route as AuthenticatedDepositRouteImport } from './routes/_authenticated/deposit'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedInvestPortfolioRouteImport } from './routes/_authenticated/invest.portfolio'
import { Route as AuthenticatedInvestNewRouteImport } from './routes/_authenticated/invest.new'
import { Route as AuthenticatedInvestEarningsRouteImport } from './routes/_authenticated/invest.earnings'
import { Route as AuthenticatedAdminWithdrawalsRouteImport } from './routes/_authenticated/admin/withdrawals'
import { Route as AuthenticatedAdminWalletsRouteImport } from './routes/_authenticated/admin/wallets'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminReferralsRouteImport } from './routes/_authenticated/admin/referrals'
import { Route as AuthenticatedAdminPlansRouteImport } from './routes/_authenticated/admin/plans'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin/notifications'
import { Route as AuthenticatedAdminDepositsRouteImport } from './routes/_authenticated/admin/deposits'
import { Route as AuthenticatedInvestDepositIdRouteImport } from './routes/_authenticated/invest.deposit.$id'
import { Route as AuthenticatedInvestDepositIdProofRouteImport } from './routes/_authenticated/invest.deposit.$id.proof'
import { Route as AuthenticatedInvestDepositIdConfirmRouteImport } from './routes/_authenticated/invest.deposit.$id.confirm'

const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWithdrawRoute = AuthenticatedWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReferralsRoute = AuthenticatedReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvestRoute = AuthenticatedInvestRouteImport.update({
  id: '/invest',
  path: '/invest',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDepositRoute = AuthenticatedDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedInvestPortfolioRoute =
  AuthenticatedInvestPortfolioRouteImport.update({
    id: '/portfolio',
    path: '/portfolio',
    getParentRoute: () => AuthenticatedInvestRoute,
  } as any)
const AuthenticatedInvestNewRoute = AuthenticatedInvestNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedInvestRoute,
} as any)
const AuthenticatedInvestEarningsRoute =
  AuthenticatedInvestEarningsRouteImport.update({
    id: '/earnings',
    path: '/earnings',
    getParentRoute: () => AuthenticatedInvestRoute,
  } as any)
const AuthenticatedAdminWithdrawalsRoute =
  AuthenticatedAdminWithdrawalsRouteImport.update({
    id: '/withdrawals',
    path: '/withdrawals',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminWalletsRoute =
  AuthenticatedAdminWalletsRouteImport.update({
    id: '/wallets',
    path: '/wallets',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminReferralsRoute =
  AuthenticatedAdminReferralsRouteImport.update({
    id: '/referrals',
    path: '/referrals',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPlansRoute = AuthenticatedAdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDepositsRoute =
  AuthenticatedAdminDepositsRouteImport.update({
    id: '/deposits',
    path: '/deposits',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedInvestDepositIdRoute =
  AuthenticatedInvestDepositIdRouteImport.update({
    id: '/deposit/$id',
    path: '/deposit/$id',
    getParentRoute: () => AuthenticatedInvestRoute,
  } as any)
const AuthenticatedInvestDepositIdProofRoute =
  AuthenticatedInvestDepositIdProofRouteImport.update({
    id: '/proof',
    path: '/proof',
    getParentRoute: () => AuthenticatedInvestDepositIdRoute,
  } as any)
const AuthenticatedInvestDepositIdConfirmRoute =
  AuthenticatedInvestDepositIdConfirmRouteImport.update({
    id: '/confirm',
    path: '/confirm',
    getParentRoute: () => AuthenticatedInvestDepositIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/plans': typeof PlansRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deposit': typeof AuthenticatedDepositRoute
  '/invest': typeof AuthenticatedInvestRouteWithChildren
  '/referrals': typeof AuthenticatedReferralsRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
  '/admin/deposits': typeof AuthenticatedAdminDepositsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/referrals': typeof AuthenticatedAdminReferralsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/wallets': typeof AuthenticatedAdminWalletsRoute
  '/admin/withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/invest/earnings': typeof AuthenticatedInvestEarningsRoute
  '/invest/new': typeof AuthenticatedInvestNewRoute
  '/invest/portfolio': typeof AuthenticatedInvestPortfolioRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/invest/deposit/$id': typeof AuthenticatedInvestDepositIdRouteWithChildren
  '/invest/deposit/$id/confirm': typeof AuthenticatedInvestDepositIdConfirmRoute
  '/invest/deposit/$id/proof': typeof AuthenticatedInvestDepositIdProofRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/plans': typeof PlansRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deposit': typeof AuthenticatedDepositRoute
  '/invest': typeof AuthenticatedInvestRouteWithChildren
  '/referrals': typeof AuthenticatedReferralsRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
  '/admin/deposits': typeof AuthenticatedAdminDepositsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/referrals': typeof AuthenticatedAdminReferralsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/wallets': typeof AuthenticatedAdminWalletsRoute
  '/admin/withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/invest/earnings': typeof AuthenticatedInvestEarningsRoute
  '/invest/new': typeof AuthenticatedInvestNewRoute
  '/invest/portfolio': typeof AuthenticatedInvestPortfolioRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/invest/deposit/$id': typeof AuthenticatedInvestDepositIdRouteWithChildren
  '/invest/deposit/$id/confirm': typeof AuthenticatedInvestDepositIdConfirmRoute
  '/invest/deposit/$id/proof': typeof AuthenticatedInvestDepositIdProofRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/plans': typeof PlansRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/deposit': typeof AuthenticatedDepositRoute
  '/_authenticated/invest': typeof AuthenticatedInvestRouteWithChildren
  '/_authenticated/referrals': typeof AuthenticatedReferralsRoute
  '/_authenticated/withdraw': typeof AuthenticatedWithdrawRoute
  '/_authenticated/admin/deposits': typeof AuthenticatedAdminDepositsRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/_authenticated/admin/referrals': typeof AuthenticatedAdminReferralsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/wallets': typeof AuthenticatedAdminWalletsRoute
  '/_authenticated/admin/withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/_authenticated/invest/earnings': typeof AuthenticatedInvestEarningsRoute
  '/_authenticated/invest/new': typeof AuthenticatedInvestNewRoute
  '/_authenticated/invest/portfolio': typeof AuthenticatedInvestPortfolioRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/invest/deposit/$id': typeof AuthenticatedInvestDepositIdRouteWithChildren
  '/_authenticated/invest/deposit/$id/confirm': typeof AuthenticatedInvestDepositIdConfirmRoute
  '/_authenticated/invest/deposit/$id/proof': typeof AuthenticatedInvestDepositIdProofRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/plans'
    | '/admin'
    | '/dashboard'
    | '/deposit'
    | '/invest'
    | '/referrals'
    | '/withdraw'
    | '/admin/deposits'
    | '/admin/notifications'
    | '/admin/plans'
    | '/admin/referrals'
    | '/admin/users'
    | '/admin/wallets'
    | '/admin/withdrawals'
    | '/invest/earnings'
    | '/invest/new'
    | '/invest/portfolio'
    | '/admin/'
    | '/invest/deposit/$id'
    | '/invest/deposit/$id/confirm'
    | '/invest/deposit/$id/proof'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/plans'
    | '/dashboard'
    | '/deposit'
    | '/invest'
    | '/referrals'
    | '/withdraw'
    | '/admin/deposits'
    | '/admin/notifications'
    | '/admin/plans'
    | '/admin/referrals'
    | '/admin/users'
    | '/admin/wallets'
    | '/admin/withdrawals'
    | '/invest/earnings'
    | '/invest/new'
    | '/invest/portfolio'
    | '/admin'
    | '/invest/deposit/$id'
    | '/invest/deposit/$id/confirm'
    | '/invest/deposit/$id/proof'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/plans'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/deposit'
    | '/_authenticated/invest'
    | '/_authenticated/referrals'
    | '/_authenticated/withdraw'
    | '/_authenticated/admin/deposits'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/plans'
    | '/_authenticated/admin/referrals'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/wallets'
    | '/_authenticated/admin/withdrawals'
    | '/_authenticated/invest/earnings'
    | '/_authenticated/invest/new'
    | '/_authenticated/invest/portfolio'
    | '/_authenticated/admin/'
    | '/_authenticated/invest/deposit/$id'
    | '/_authenticated/invest/deposit/$id/confirm'
    | '/_authenticated/invest/deposit/$id/proof'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PlansRoute: typeof PlansRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/withdraw': {
      id: '/_authenticated/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof AuthenticatedWithdrawRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/referrals': {
      id: '/_authenticated/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AuthenticatedReferralsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invest': {
      id: '/_authenticated/invest'
      path: '/invest'
      fullPath: '/invest'
      preLoaderRoute: typeof AuthenticatedInvestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/deposit': {
      id: '/_authenticated/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof AuthenticatedDepositRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/invest/portfolio': {
      id: '/_authenticated/invest/portfolio'
      path: '/portfolio'
      fullPath: '/invest/portfolio'
      preLoaderRoute: typeof AuthenticatedInvestPortfolioRouteImport
      parentRoute: typeof AuthenticatedInvestRoute
    }
    '/_authenticated/invest/new': {
      id: '/_authenticated/invest/new'
      path: '/new'
      fullPath: '/invest/new'
      preLoaderRoute: typeof AuthenticatedInvestNewRouteImport
      parentRoute: typeof AuthenticatedInvestRoute
    }
    '/_authenticated/invest/earnings': {
      id: '/_authenticated/invest/earnings'
      path: '/earnings'
      fullPath: '/invest/earnings'
      preLoaderRoute: typeof AuthenticatedInvestEarningsRouteImport
      parentRoute: typeof AuthenticatedInvestRoute
    }
    '/_authenticated/admin/withdrawals': {
      id: '/_authenticated/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AuthenticatedAdminWithdrawalsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/wallets': {
      id: '/_authenticated/admin/wallets'
      path: '/wallets'
      fullPath: '/admin/wallets'
      preLoaderRoute: typeof AuthenticatedAdminWalletsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/referrals': {
      id: '/_authenticated/admin/referrals'
      path: '/referrals'
      fullPath: '/admin/referrals'
      preLoaderRoute: typeof AuthenticatedAdminReferralsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/plans': {
      id: '/_authenticated/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AuthenticatedAdminPlansRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/deposits': {
      id: '/_authenticated/admin/deposits'
      path: '/deposits'
      fullPath: '/admin/deposits'
      preLoaderRoute: typeof AuthenticatedAdminDepositsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/invest/deposit/$id': {
      id: '/_authenticated/invest/deposit/$id'
      path: '/deposit/$id'
      fullPath: '/invest/deposit/$id'
      preLoaderRoute: typeof AuthenticatedInvestDepositIdRouteImport
      parentRoute: typeof AuthenticatedInvestRoute
    }
    '/_authenticated/invest/deposit/$id/proof': {
      id: '/_authenticated/invest/deposit/$id/proof'
      path: '/proof'
      fullPath: '/invest/deposit/$id/proof'
      preLoaderRoute: typeof AuthenticatedInvestDepositIdProofRouteImport
      parentRoute: typeof AuthenticatedInvestDepositIdRoute
    }
    '/_authenticated/invest/deposit/$id/confirm': {
      id: '/_authenticated/invest/deposit/$id/confirm'
      path: '/confirm'
      fullPath: '/invest/deposit/$id/confirm'
      preLoaderRoute: typeof AuthenticatedInvestDepositIdConfirmRouteImport
      parentRoute: typeof AuthenticatedInvestDepositIdRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminDepositsRoute: typeof AuthenticatedAdminDepositsRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminPlansRoute: typeof AuthenticatedAdminPlansRoute
  AuthenticatedAdminReferralsRoute: typeof AuthenticatedAdminReferralsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminWalletsRoute: typeof AuthenticatedAdminWalletsRoute
  AuthenticatedAdminWithdrawalsRoute: typeof AuthenticatedAdminWithdrawalsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminDepositsRoute: AuthenticatedAdminDepositsRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminPlansRoute: AuthenticatedAdminPlansRoute,
  AuthenticatedAdminReferralsRoute: AuthenticatedAdminReferralsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminWalletsRoute: AuthenticatedAdminWalletsRoute,
  AuthenticatedAdminWithdrawalsRoute: AuthenticatedAdminWithdrawalsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedInvestDepositIdRouteChildren {
  AuthenticatedInvestDepositIdConfirmRoute: typeof AuthenticatedInvestDepositIdConfirmRoute
  AuthenticatedInvestDepositIdProofRoute: typeof AuthenticatedInvestDepositIdProofRoute
}

const AuthenticatedInvestDepositIdRouteChildren: AuthenticatedInvestDepositIdRouteChildren =
  {
    AuthenticatedInvestDepositIdConfirmRoute:
      AuthenticatedInvestDepositIdConfirmRoute,
    AuthenticatedInvestDepositIdProofRoute:
      AuthenticatedInvestDepositIdProofRoute,
  }

const AuthenticatedInvestDepositIdRouteWithChildren =
  AuthenticatedInvestDepositIdRoute._addFileChildren(
    AuthenticatedInvestDepositIdRouteChildren,
  )

interface AuthenticatedInvestRouteChildren {
  AuthenticatedInvestEarningsRoute: typeof AuthenticatedInvestEarningsRoute
  AuthenticatedInvestNewRoute: typeof AuthenticatedInvestNewRoute
  AuthenticatedInvestPortfolioRoute: typeof AuthenticatedInvestPortfolioRoute
  AuthenticatedInvestDepositIdRoute: typeof AuthenticatedInvestDepositIdRouteWithChildren
}

const AuthenticatedInvestRouteChildren: AuthenticatedInvestRouteChildren = {
  AuthenticatedInvestEarningsRoute: AuthenticatedInvestEarningsRoute,
  AuthenticatedInvestNewRoute: AuthenticatedInvestNewRoute,
  AuthenticatedInvestPortfolioRoute: AuthenticatedInvestPortfolioRoute,
  AuthenticatedInvestDepositIdRoute:
    AuthenticatedInvestDepositIdRouteWithChildren,
}

const AuthenticatedInvestRouteWithChildren =
  AuthenticatedInvestRoute._addFileChildren(AuthenticatedInvestRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepositRoute: typeof AuthenticatedDepositRoute
  AuthenticatedInvestRoute: typeof AuthenticatedInvestRouteWithChildren
  AuthenticatedReferralsRoute: typeof AuthenticatedReferralsRoute
  AuthenticatedWithdrawRoute: typeof AuthenticatedWithdrawRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepositRoute: AuthenticatedDepositRoute,
  AuthenticatedInvestRoute: AuthenticatedInvestRouteWithChildren,
  AuthenticatedReferralsRoute: AuthenticatedReferralsRoute,
  AuthenticatedWithdrawRoute: AuthenticatedWithdrawRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PlansRoute: PlansRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
